version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=myadmin
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '8080:8080'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
